name:                ext-irc-bot
version:             0.1.0.0
github:              "t4ccer/ext-irc-bot"
license:             BSD3
author:              "t4ccer"
maintainer:          "t4ccer@gmail.com"
copyright:           "2020 t4ccer"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/t4ccer/ext-irc-bot#readme>

dependencies:
- base >= 4.14.0 && < 4.14.1
- bytestring
- network 
- string-interpolate
- megaparsec 

library:
  source-dirs: src

executables:
  ext-irc-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fwarn-unused-do-bind
    dependencies:
    - ext-irc-bot
